
## Comparing summaries for exp 1 and exp 2
```{r}
# par(mfrow = c(1,3))
# summary(Z1P) # Plant biomass Z=100
# summary(Z2P) # Plant biomass Z=250
# summary(Z3P) # Plant biomass Z=500
# 
# summary(Z1M) # soil moisture Z=100
# summary(Z2M) # soil moisture Z=250
# summary(Z3M) # soil moisture Z=500
# 
# summary(Z1SmM) # soil salt mass Z=100
# summary(Z2SmM) # soil salt mass Z=250
# summary(Z3SmM) # soil salt mass Z=500
# 
# summary(Z1CM) # soil salt concentration Z=100
# summary(Z2CM) # soil salt concentration Z=250
# summary(Z3CM) # soil salt concentration Z=500
``` 

## Comparing the distributions for exp 1 and 2
```{r}

par(mfrow = c(1,3))
hist(Z1P, breaks=10, main = 'Plant biomass Z=100')
hist(Z2P, breaks=10, main = 'Plant biomass Z=250')
hist(Z2P, breaks=10, main = 'Plant biomass Z=500')

hist(Z1M, breaks=10,main="Soil moisture Z=100")
hist(Z2M, breaks=10,main="Soil moisture Z=250")
hist(Z3M, breaks=10,main="Soil moisture Z=500")

hist(Z1SmM, breaks=10,main="soil salt mass Z=100")
hist(Z2SmM, breaks=10,main="soil salt mass Z=250")
hist(Z3SmM, breaks=10,main="soil salt mass Z=500")


hist(Z1CM, breaks=10, main="Salt concentration in soil Z=100")
hist(Z2CM, breaks=10, main="Salt concentration in soil Z=250")
hist(Z3CM, breaks=10, main="Salt concentration in soil Z=500")

```

## Testing whether distributions for exp 1 and 2 are significantly different from each other
```{r}
wilcox.test(Z1M,Z2M) # soil moisture
wilcox.test(Z2M,Z3M) # soil moisture
wilcox.test(Z1M,Z3M) # soil moisture

wilcox.test(Z1P,Z2P) # Plant biomass
wilcox.test(Z2P,Z3P) # Plant biomass
wilcox.test(Z1P,Z3P) # Plant biomass

wilcox.test(Z1SmM,Z2SmM) # soil salt mass
wilcox.test(Z2SmM,Z3SmM) # soil salt mass
wilcox.test(Z1SmM,Z3SmM) # soil salt mass

wilcox.test(Z1CM,Z2CM) # salt conc
wilcox.test(Z2CM,Z3CM) # salt conc
wilcox.test(Z1CM,Z3CM) # salt conc

```

## Conclusive remarks
